name: sociableapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  custom_navigation_bar: ^0.8.0
  eva_icons_flutter: ^3.0.0
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.7
  image_picker: ^0.8.4
  page_transition: ^2.0.2
  circular_countdown_timer: ^0.2.0
  provider: ^6.0.0
  flutter_login_facebook: ^1.0.1
  lottie : ^1.2.0
  timeago : ^3.0.1
  nanoid: ^1.0.0
  flutter_launcher_icons : ^0.9.1
  flutter_windowmanager : ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path : "assets/icons/appicon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/appicon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

    - family: Monteserrat
      fonts:
        - asset: assets/fonts/Monteserat.ttf
